import React from 'react';
import { Link } from '../router.js';
import { SITE } from '../config.js';
import SocialLinks from './SocialLinks.js';

export default function Footer() {
  return React.createElement('footer', { className: 'site-footer' },
    React.createElement('div', { className: 'wrap' },
      React.createElement('div', { className: 'footer-grid' },
        React.createElement('div', null,
          React.createElement('div', { className: 'footer-brand' },
            React.createElement('img', { src: './assets/logo-dark.png', alt: SITE.name, className: 'brand-logo' }),
          ),
          React.createElement('p', { className: 'footer-tagline' }, SITE.tagline),
          React.createElement(SocialLinks, { size: 18, className: 'footer-social' }),
        ),
        React.createElement('div', null,
          React.createElement('div', { className: 'footer-col-title' }, 'Servicios'),
          React.createElement('div', { className: 'footer-col' },
            React.createElement(Link, { to: '/servicios' }, 'Agencia aduanal'),
            React.createElement(Link, { to: '/servicios' }, 'Comercializadora'),
            React.createElement(Link, { to: '/servicios' }, 'Logística y fletes'),
            React.createElement(Link, { to: '/servicios' }, 'Asesoría'),
          ),
        ),
        React.createElement('div', null,
          React.createElement('div', { className: 'footer-col-title' }, 'Recursos'),
          React.createElement('div', { className: 'footer-col' },
            React.createElement('span', null, 'La Guía Maestra'),
            React.createElement(Link, { to: '/preguntas-frecuentes' }, 'Preguntas frecuentes'),
            React.createElement(Link, { to: '/foro' }, 'Foro'),
          ),
        ),
        React.createElement('div', null,
          React.createElement('div', { className: 'footer-col-title' }, 'Contacto'),
          React.createElement('div', { className: 'footer-col' },
            React.createElement('a', { href: SITE.phoneHref }, SITE.phoneDisplay),
            React.createElement('a', { href: `mailto:${SITE.email}` }, SITE.email),
            React.createElement('span', null, SITE.city),
          ),
        ),
      ),
      React.createElement('div', { className: 'footer-bottom' },
        React.createElement('span', null, `© ${new Date().getFullYear()} ${SITE.name}. Todos los derechos reservados.`),
        React.createElement('span', null, 'Aviso de privacidad'),
      ),
    ),
  );
}
